#!/bin/bash
# Make hardlinks to home directory.
# - Workplace agnostic.

# Get the pwd of this script.
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Default to diff each file before overwriting. -a or --all doesn't diff.
WRITEALL=0
[[ $1 =~ ^-a$ ]] || [[ $1 =~ ^--all$ ]] && WRITEALL=1 && shift

DOTFILES="ackrc agignore aliases bash_profile completion functions gcloudrc gitattributes gitconfig gitignore go node path prompt python ruby vars vimrc"

# Get workplace/section specific dotfiles
for INSTALLFILE in $@; do
    if [[ -e $DIR/$INSTALLFILE-install ]]; then
        DOTFILES+=" $(cat $DIR/$INSTALLFILE-install)"
    else
        echo "$INSTALLFILE-install doesn't exist"
    fi
done

# Install files to home directory using dotfile-linker.sh.
source $DIR/dotfile-linker.sh
if [ $WRITEALL -eq 1 ]; then
    dotfileLinkAll $DIR $DOTFILES
else
    dotfileLink $DIR $DOTFILES
fi

# Setup nvm default global packages to install.
if [ -z "${NVM_DIR+x}" ]; then
    source ./node
fi
ln -sf $DIR/node-default-globals.txt $NVM_DIR/default-packages

which diff-so-fancy 2>&1 >/dev/null || (echo "Installing diff-so-fancy" && brew install diff-so-fancy)
